export {default as Hero}from "./Hero"
export {default as Navbar}from "./Navbar"
export {default as Partners}from "./Partners"
export {default as Features}from "./Features"
export {default as About}from "./About"
export {default as Managment}from "./Managment"
export {default as OurFeature}from "./OurFeature"